#!/bin/bash
# install service in dev container

cd /workspace

# upgrade pip
python -m pip install --upgrade pip

# install in edit mode with testing dependencies
pip install -e .[all]

# install dev dependencies
pip install -r requirements-dev.txt

# install pre-commit hooks to git:
pre-commit install
